config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  resources :product_to_orders
  resources :class_variables
  resources :orders
  resources :products
  resources :couriers
  resources :employees
  resources :volonteers
   get 'login', to: 'sessions#new'   
   post 'login', to: 'sessions#create'
   get 'create_user', to: 'sessions#create_user'
   post 'create_user', to: 'sessions#create_user_confirm'
   get 'welcome', to: 'sessions#welcome'
   get 'create_order', to: 'products#create_order'
   post 'create_order_check', to: 'products#create_order_check'
   get 'order_completed', to: 'products#order_complited'
   get 'profile' , to: "sessions#showprofile"
   get 'restricted', to: "sessions#access_restricted"
   get 'order_details', to: "orders#detail"
end

app/models/class_variable.rb
class ClassVariable < ApplicationRecord
end

app/controllers/class_variables_controller.rb
class ClassVariablesController < ApplicationController
  before_action :set_class_variable, only: [:show, :edit, :update, :destroy]

  # GET /class_variables
  # GET /class_variables.json
  def index
    @class_variables = ClassVariable.all
  end

  # GET /class_variables/1
  # GET /class_variables/1.json
  def show
  end

  # GET /class_variables/new
  def new
    @class_variable = ClassVariable.new
  end

  # GET /class_variables/1/edit
  def edit
  end

  # POST /class_variables
  # POST /class_variables.json
  def create
    @class_variable = ClassVariable.new(class_variable_params)

    respond_to do |format|
      if @class_variable.save
        format.html { redirect_to @class_variable, notice: 'Class variable was successfully created.' }
        format.json { render :show, status: :created, location: @class_variable }
      else
        format.html { render :new }
        format.json { render json: @class_variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_variables/1
  # PATCH/PUT /class_variables/1.json
  def update
    respond_to do |format|
      if @class_variable.update(class_variable_params)
        format.html { redirect_to @class_variable, notice: 'Class variable was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_variable }
      else
        format.html { render :edit }
        format.json { render json: @class_variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_variables/1
  # DELETE /class_variables/1.json
  def destroy
    @class_variable.destroy
    respond_to do |format|
      format.html { redirect_to class_variables_url, notice: 'Class variable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_variable
      @class_variable = ClassVariable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def class_variable_params
      params.require(:class_variable).permit(:orders_number)
    end
end

app/helpers/class_variables_helper.rb
module ClassVariablesHelper
end

app/views/class_variables/_form.html.erb
<%= form_with(model: class_variable, local: true) do |form| %>
  <% if class_variable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class_variable.errors.count, "error") %> prohibited this class_variable from being saved:</h2>

      <ul>
      <% class_variable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :orders_number %>
    <%= form.number_field :orders_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/class_variables/edit.html.erb
<h1>Editing Class Variable</h1>

<%= render 'form', class_variable: @class_variable %>

<%= link_to 'Show', @class_variable %> |
<%= link_to 'Back', class_variables_path %>

app/views/class_variables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Class Variables</h1>

<table>
  <thead>
    <tr>
      <th>Orders number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_variables.each do |class_variable| %>
      <tr>
        <td><%= class_variable.orders_number %></td>
        <td><%= link_to 'Show', class_variable %></td>
        <td><%= link_to 'Edit', edit_class_variable_path(class_variable) %></td>
        <td><%= link_to 'Destroy', class_variable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class Variable', new_class_variable_path %>

app/views/class_variables/new.html.erb
<h1>New Class Variable</h1>

<%= render 'form', class_variable: @class_variable %>

<%= link_to 'Back', class_variables_path %>

app/views/class_variables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Orders number:</strong>
  <%= @class_variable.orders_number %>
</p>

<%= link_to 'Edit', edit_class_variable_path(@class_variable) %> |
<%= link_to 'Back', class_variables_path %>