config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  resources :product_to_orders
  resources :class_variables
  resources :orders
  resources :products
  resources :couriers
  resources :employees
  resources :volonteers
   get 'login', to: 'sessions#new'   
   post 'login', to: 'sessions#create'
   get 'create_user', to: 'sessions#create_user'
   post 'create_user', to: 'sessions#create_user_confirm'
   get 'welcome', to: 'sessions#welcome'
   get 'create_order', to: 'products#create_order'
   post 'create_order_check', to: 'products#create_order_check'
   get 'order_completed', to: 'products#order_complited'
   get 'profile' , to: "sessions#showprofile"
   get 'restricted', to: "sessions#access_restricted"
   get 'order_details', to: "orders#detail"
end

app/models/volonteer.rb
class Volonteer < ApplicationRecord
end

app/controllers/volonteers_controller.rb
class VolonteersController < ApplicationController
  before_action :set_volonteer, only: [:show, :edit, :update, :destroy]

  # GET /volonteers
  # GET /volonteers.json
  def index
    @volonteers = Volonteer.all
  end

  # GET /volonteers/1
  # GET /volonteers/1.json
  def show
  end

  # GET /volonteers/new
  def new
    @volonteer = Volonteer.new
  end

  # GET /volonteers/1/edit
  def edit
  end

  # POST /volonteers
  # POST /volonteers.json
  def create
    @volonteer = Volonteer.new(volonteer_params)

    respond_to do |format|
      if @volonteer.save
        format.html { redirect_to @volonteer, notice: 'Volonteer was successfully created.' }
        format.json { render :show, status: :created, location: @volonteer }
      else
        format.html { render :new }
        format.json { render json: @volonteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volonteers/1
  # PATCH/PUT /volonteers/1.json
  def update
    respond_to do |format|
      if @volonteer.update(volonteer_params)
        format.html { redirect_to @volonteer, notice: 'Volonteer was successfully updated.' }
        format.json { render :show, status: :ok, location: @volonteer }
      else
        format.html { render :edit }
        format.json { render json: @volonteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volonteers/1
  # DELETE /volonteers/1.json
  def destroy
    @volonteer.destroy
    respond_to do |format|
      format.html { redirect_to volonteers_url, notice: 'Volonteer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volonteer
      @volonteer = Volonteer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def volonteer_params
      params.require(:volonteer).permit(:name,:surname,:login,:password)
    end
end

app/helpers/volonteers_helper.rb
module VolonteersHelper
end

app/views/volonteers/_form.html.erb
<%= form_with(model: volonteer, local: true) do |form| %>
  <% if volonteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(volonteer.errors.count, "error") %> prohibited this volonteer from being saved:</h2>

      <ul>
      <% volonteer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :surname %>
    <%= form.text_field :surname %>
    <%= form.label :login %>
    <%= form.text_field :login%>
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/volonteers/edit.html.erb
<h1>Editing Volonteer</h1>

<%= render 'form', volonteer: @volonteer %>

<%= link_to 'Show', @volonteer %> |
<%= link_to 'Back', volonteers_path %>

app/views/volonteers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Volonteers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @volonteers.each do |volonteer| %>
      <tr>
        <td><%= volonteer.name %></td>
        <td><%= link_to 'Show', volonteer %></td>
        <td><%= link_to 'Edit', edit_volonteer_path(volonteer) %></td>
        <td><%= link_to 'Destroy', volonteer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Volonteer', new_volonteer_path %>

app/views/volonteers/new.html.erb
<h1>New Volonteer</h1>

<%= render 'form', volonteer: @volonteer %>

<%= link_to 'Back', volonteers_path %>

app/views/volonteers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @volonteer.name %>
</p>

<%= link_to 'Edit', edit_volonteer_path(@volonteer) %> |
<%= link_to 'Back', volonteers_path %>